### ISSUE TITLE
How do you use it ?

### ISSUE THREAD

**Issue by keplerk** [Karyoplasma/Fallout4CharacterPlanner#1]
As the title says, how do you use/implement it ?

**Comment by Karyoplasma** [comment]
Go to the [release page](https://github.com/Karyoplasma/Fallout4CharacterPlanner/releases/tag/1.0.0) and download the ZIP-file. The .jar-file contained inside is runnable as long as you have Java installed on your computer.

Keep in mind that I have not updated this in a long time, so Nuka-World DLC perks, e.g. the second rank of VANS granting +2 Perception, are not selectable. The ZIP from the release also contains the uncompiled source in the src folder (basically the same as you can browse here in the Code section on github). If you do get around to fix the missing perks, let me know and send a pull request.

**Comment by keplerk** [comment]
Thanks, and my bad i didn't see the main method on CharacterPlannerGui  🤦‍♂️

**Comment by keplerk** [comment]
My bad but I can't see any problem with Nuka-World DLC Perks, VANS rank 2 works properly.
I'm not getting something ?

https://user-images.githubusercontent.com/4659797/197421657-d747d3c2-e04d-4a41-9ab8-00662d8bb8f6.mp4

**Comment by Karyoplasma** [comment]
Hmm, maybe I actually fixed it at some point xD
It was a long time ago when I coded this, I just remember discovering something was missing and I was too lazy to fix it. Maybe you'll find out, maybe it was some obscure interaction, I don't know.

All in all, the planner will still work correctly because the perk system in FO4 never changed. The UI was blatantly "inspired" from a website I used back then but it didn't have bobbleheads or other stat minmaxing (like start off with 11 in a stat due to the SPECIAL book) functionality, so I wrote this. I even remember emailing the owner of the site and asking if it was okay to rip off their UI design and they said yeah.
